/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Documentation",
  "tagline": "Rookout - Get data on-demand from your live code just when you need it.",
  "url": "https://docs.rookout.com",
  "baseUrl": "/",
  "organizationName": "Rookout",
  "projectName": "docs",
  "scripts": [
    "https://cdn.logrocket.io/LogRocket.min.js",
    "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js",
    "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js",
    "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js",
    "https://buttons.github.io/buttons.js",
    "https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js",
    "https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js",
    "/js/rookoutCustom.js",
    "/js/code-blocks-buttons.js"
  ],
  "stylesheets": [
    "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  ],
  "favicon": "img/logos/bird_logo.png",
  "customFields": {
    "fonts": {
      "rookoutFont": [
        "Roboto",
        "sans-serif"
      ]
    },
    "markdownPlugins": [
      null
    ],
    "repoUrl": "https://github.com/Rookout/docs"
  },
  "onBrokenLinks": "log",
  "onBrokenMarkdownLinks": "log",
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "editUrl": "https://github.com/Rookout/docs/edit/master/docs/",
          "path": "../docs",
          "sidebarPath": "../website/sidebars.json"
        },
        "blog": {},
        "theme": {
          "customCss": [
            "/Users/ryan/Desktop/projects/docs/website/src/css/custom.css"
          ]
        }
      }
    ]
  ],
  "plugins": [
    [
      "/Users/ryan/Desktop/projects/docs/website/node_modules/@cmfcmf/docusaurus-search-local/lib/server/index.js",
      {
        "maxSearchResults": 12
      }
    ]
  ],
  "themeConfig": {
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "title": "Documentation",
      "logo": {
        "target": "_self",
        "href": "/docs/welcome",
        "src": "img/logos/bird_logo_white.svg"
      },
      "items": [],
      "hideOnScroll": false
    },
    "footer": {
      "links": [
        {
          "title": "General",
          "items": [
            {
              "label": "welcome",
              "to": "/docs/welcome"
            },
            {
              "label": "use cases",
              "to": "/docs/use-cases"
            },
            {
              "label": "setup guide",
              "to": "/docs/setup-guide"
            }
          ]
        },
        {
          "title": "Tutorials",
          "items": [
            {
              "label": "java container-tutorial",
              "to": "/docs/java-container-tutorial"
            },
            {
              "label": "node container-tutorial",
              "to": "/docs/node-container-tutorial"
            },
            {
              "label": "python container-tutorial",
              "to": "/docs/python-container-tutorial"
            },
            {
              "label": "dotnet container-tutorial",
              "to": "/docs/dotnet-container-tutorial"
            },
            {
              "label": "ruby container-tutorial",
              "to": "/docs/ruby-container-tutorial"
            }
          ]
        },
        {
          "title": "SDK Setup",
          "items": [
            {
              "label": "setup intro",
              "to": "/docs/setup-intro"
            },
            {
              "label": "jvm setup",
              "to": "/docs/jvm-setup"
            },
            {
              "label": "dotnet setup",
              "to": "/docs/dotnet-setup"
            },
            {
              "label": "python setup",
              "to": "/docs/python-setup"
            },
            {
              "label": "ruby setup",
              "to": "/docs/ruby-setup"
            },
            {
              "label": "node setup",
              "to": "/docs/node-setup"
            },
            {
              "label": "go setup",
              "to": "/docs/go-setup"
            },
            {
              "label": "deployment examples",
              "to": "/docs/deployment-examples"
            }
          ]
        },
        {
          "title": "Session Configuration",
          "items": [
            {
              "label": "debug session-setup",
              "to": "/docs/debug-session-setup"
            },
            {
              "label": "source repos",
              "to": "/docs/source-repos"
            },
            {
              "label": "projects labels",
              "to": "/docs/projects-labels"
            }
          ]
        },
        {
          "title": "Breakpoints",
          "items": [
            {
              "label": "breakpoints",
              "to": "/docs/breakpoints"
            },
            {
              "label": "breakpoints status",
              "to": "/docs/breakpoints-status"
            },
            {
              "label": "breakpoints conditional",
              "to": "/docs/breakpoints-conditional"
            },
            {
              "label": "breakpoint limits",
              "to": "/docs/breakpoint-limits"
            },
            {
              "label": "built in-variables",
              "to": "/docs/built-in-variables"
            }
          ]
        },
        {
          "title": "Organizations",
          "items": [
            {
              "label": "organizations",
              "to": "/docs/organizations"
            }
          ]
        },
        {
          "title": "ETL Controller",
          "items": [
            {
              "label": "etl controller-intro",
              "to": "/docs/etl-controller-intro"
            },
            {
              "label": "etl controller-install",
              "to": "/docs/etl-controller-install"
            },
            {
              "label": "etl controller-config",
              "to": "/docs/etl-controller-config"
            }
          ]
        },
        {
          "title": "Data On-Premise",
          "items": [
            {
              "label": "dop intro",
              "to": "/docs/dop-intro"
            },
            {
              "label": "dop install",
              "to": "/docs/dop-install"
            },
            {
              "label": "dop config",
              "to": "/docs/dop-config"
            }
          ]
        },
        {
          "title": "Advanced",
          "items": [
            {
              "label": "live logger",
              "to": "/docs/live-logger"
            },
            {
              "label": "collaborations",
              "to": "/docs/collaborations"
            },
            {
              "label": "tracing timeline",
              "to": "/docs/tracing-timeline"
            },
            {
              "label": "keyboard shortcuts",
              "to": "/docs/keyboard-shortcuts"
            },
            {
              "label": "data redaction",
              "to": "/docs/data-redaction"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "sdk digests",
              "to": "/docs/sdk-digests"
            },
            {
              "label": "license",
              "to": "/docs/license"
            }
          ]
        },
        {
          "title": "Other",
          "items": [
            {
              "label": "Status",
              "href": "https://status.rookout.com/"
            }
          ]
        },
        {
          "title": "Social",
          "items": [
            {
              "html": "<div class=\"social-wrapper\"> \n\n         <a class=\"social-icon\" href=\"https://github.com/Rookout\" target=\"_blank\"><img src=\"/img/social/github.svg\" alt=\"GitHub - Rookout\"></a>\n         <a class=\"social-icon\" href=\"https://www.facebook.com/rookoutlabs/\" target=\"_blank\"><img src=\"/img/social/facebook.svg\" alt=\"Facebook - Rookout\"></a>\n         <a class=\"social-icon\" href=\"https://twitter.com/rookoutlabs\" target=\"_blank\"><img src=\"/img/social/twitter.svg\" alt=\"Twitter - Rookout\"></a>\n         <a class=\"social-icon\" href=\"https://www.linkedin.com/company/rookout/\" target=\"_blank\"><img src=\"/img/social/linkedin.svg\" alt=\"LinkedIn - Rookout\"></a>\n        </div>"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2022  Rookout",
      "style": "light"
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "themes": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
